### PR TITLE
Implemented max_docs

### PR DESCRIPTION
**Pull request by McWashr**
Per issue #56, implemented max_docs to allow easier ignoring of common terms. Updated network.py and documentation.

### CODE REVIEW

**Comment by McWashr** [comment]
Just realised this pull request failed some checks, should be linted correctly now. If I need to fix anything else just let me know!

**Comment by McWashr** [comment]
Poetry confuses me - I generated a poetry.lock file via poetry lock --no-update though this caused conflicts. I don't see any reason why the code changes should have directly or indirectly caused any dependency changes. So, if I did it correctly, I just grabbed the existing upstream poetry.lock file. Reliant on your expertise here for if this is the right action.

**Comment by McWashr** [comment]
@jboynyc Anything else I need to do or fix here? Hope you are well!

**Comment by jboynyc** [comment]
sorry, I've just been very busy with other work! I will prepare a new release with this soon.

**Comment by jboynyc** [comment]
Added to the dev branch in 3226642627701c0631823a0ed407cee889e36361 for inclusion in next release. Thanks again!

**Comment by McWashr** [comment]
Cheers @jboynyc. I would flag that it is acceptable for min_docs to equal max_docs? Benefit is marginal but it does allow one to filter to an exact frequency - potentially having niche application.

**Comment by jboynyc** [comment]
Makes sense, I hadn't considered that! I'll change it back before the release.

**Pull request closed without merging**
